title = "Khoa Nguyen"
# baseURL = 'https://hba.sid.one/'

pygmentsStyle = "github-dark"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# This is what goes in <html lang="">
languageCode = 'en-us'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# date format
dateFormat = "January 2, 2006"

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = true
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="projects"
    name = 'Projects'
    url = '/projects/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Khoa nguyen blog"
  defaultColor = "light" # set default color mode: dark or light
  description = "I'm a software developer. I have experience in Golang, Reactjs, and Nodejs. I created this blog to take notes on what I've learned."
  mainSections = ['posts']

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Khoa Nguyen"
  name = "khoa nguyen"
  description = "I'm a software developer. I have experience in Golang, Reactjs, and Nodejs. I created this blog to take notes on what I've learned."

[[params.socialIcons]]
name = "github"
url = "https://github.com/khoand10"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
